spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-localhost: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.fz.providerone.entity
  mapper-locations:
  - classpath:mapper/*.xml
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka01:8761/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-localhost: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.fz.providerone.entity
  mapper-locations:
  - classpath:mapper/*.xml
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka01:8761/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
    
  
  
  