spring:
  profiles:
    active:
    - dev
---
server:
  port: 8761 #注册中心占用8761端口,冒号后面必须要有空格
 
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-eureka-client
    
eureka:
  instance:
    hostname: eureka01  #冒号后面必须有空格
  client:
    register-with-eureka: false  #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false  #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka01:8761/eureka/
---
server:
  port: 8761  #注册中心占用8761端口,冒号后面必须要有空格

spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka01  #冒号后面必须有空格
  client:
    register-with-eureka: false  #当前的eureka-server自己不注册进服务列表中
    fetch-registry: false  #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka01:8761/eureka/
  